# .tbls.yml

# DSN (Database Source Name) to connect database
dsn: my://dbuser:password@db:3306/mydb


# Path to generate document
# Default is `dbdoc`
docPath: doc/schema

er:
  # Skip generation of ER diagram
  # Default is false
  skip: false
  # ER diagram image format
  # Default is `svg`
  format: svg
  # Add table/column comment to ER diagram
  # Default is false
  comment: false
  # Distance between tables that display relations in the ER
  # Default is 1
  distance: 3
  # ER diagram (png/jpg) font (font name, font file, font path or keyword)
  # Default is "" ( system default )

lint:
  requireColumnComment:
    enabled: true
    exclude:
      - id
      - created_at
      - updated_at
  columnCount:
    enabled: true
    max: 10