name: copy OpenAPI Schema to another-repo

on:
  push:
    branches:
      - main
    paths:
      - "openapi.spec.json"
  workflow_dispatch:

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Setup commit description
        env:
          RUN_URL: "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}"
          HEAD_COMMIT_URL: "${{ github.event.repository.html_url }}/commit/${{ github.event.after || github.sha }}"
        id: setup_description
        run: |
          echo "update GraphQL Schema file 🚀" > description.txt
          echo "" >> description.txt
          echo "created from ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}" >> description.txt
          echo "latest commit: ${{ github.event.repository.html_url }}/commit/${{ github.event.after || github.sha }}" >> description.txt
          echo "::set-output name=content::$(cat description.txt)"
      - name: Copy GraphQL Schema file
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ steps.generate_token.outputs.token }}
        with:
          source_file: "openapi.spec.json"
          destination_repo: ${{ secrets.DESTINATION_REPO }}
          destination_folder: ""
          destination_branch: "main"
          destination_branch_create: "feature/update-openapi"
          user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          user_name: "github-actions[bot]"
          commit_message: ${{ steps.setup_description.outputs.content }}
      - name: create Pull Request to another-repo
        run: |
          gh pr create \
            --title "update GraphQL Schema file " \
            --body "${{ steps.setup_description.outputs.content }}" \
            --repo ${{ secrets.DESTINATION_REPO }} \
            --base main \
            --head feature/update-openapi \
            --reviewer "${{ github.event.head_commit.committer.username || github.triggering_actor }}"
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
