name: test
on: push
jobs:
  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run test |
        run:  |
          docker volume create fastapi-graphql-db-volume
          docker volume create fastapi-graphql-poetry-volume
          docker-compose up -d --build
          docker-compose exec -T api /wait && poetry run pytest
          docker-compose down
        shell: bash

